version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Expose React's development server
    volumes:
      - ./frontend:/usr/src/app # Mount local code into the container
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes (useful for Windows/macOS)
    command: ["npm", "start"] # Run React's development server

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
