"""Add file_data_id to File_version

Revision ID: 2d61d1836403
Revises: 6017c24fb061
Create Date: 2025-04-16 14:10:29.734558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d61d1836403'
down_revision = '6017c24fb061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('file_version_file_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'file_data', ['file_data_id'], ['file_data_id'])
        batch_op.drop_column('file_id')

    with op.batch_alter_table('last_download', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('last_download_file_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'file_data', ['file_data_id'], ['file_data_id'])
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('last_download', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('last_download_file_id_fkey', 'file_data', ['file_id'], ['file_data_id'])
        batch_op.drop_column('file_data_id')

    with op.batch_alter_table('file_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('file_version_file_id_fkey', 'file_data', ['file_id'], ['file_data_id'])
        batch_op.drop_column('file_data_id')

    # ### end Alembic commands ###
