"""models file_data and file_version table changes for cearer understanding

Revision ID: 6017c24fb061
Revises: ed358c70bf1b
Create Date: 2025-04-16 12:37:40.151650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6017c24fb061'
down_revision = 'ed358c70bf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.drop_column('short_comment')

    with op.batch_alter_table('file_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=100), nullable=True))
        batch_op.drop_column('short_comment')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('short_comment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('comment')

    with op.batch_alter_table('file_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_comment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
