"""Added new column to User_Project;is_removed

Revision ID: b4735127703e
Revises: 2d61d1836403
Create Date: 2025-04-25 09:42:19.714396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4735127703e'
down_revision = '2d61d1836403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_removed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_project', schema=None) as batch_op:
        batch_op.drop_column('is_removed')

    # ### end Alembic commands ###
