"""Add nickname_id to User_profile

Revision ID: e2e3385983bc
Revises: 
Create Date: 2025-05-05 13:14:28.368400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2e3385983bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_project', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('reader', 'editor', 'admin', 'owner', name='role_enum'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_project', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('reader', 'editor', 'admin', 'owner', name='role_enum'),
               nullable=False)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('nickname_id')

    # ### end Alembic commands ###
