"""Upgraded the short comment max size

Revision ID: ed358c70bf1b
Revises: e2c87a90b3fa
Create Date: 2025-04-15 08:39:17.398523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed358c70bf1b'
down_revision = 'e2c87a90b3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_data', schema=None) as batch_op:
        batch_op.alter_column('short_comment',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('file_version', schema=None) as batch_op:
        batch_op.alter_column('short_comment',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_version', schema=None) as batch_op:
        batch_op.alter_column('short_comment',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('file_data', schema=None) as batch_op:
        batch_op.alter_column('short_comment',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
